import { DeviceDataKind } from "./Devices";
import { Dimmer } from "../DeviceComponents/Dimmer";
import { LightSwitch } from "../DeviceComponents/LightSwitch";
import { Contact, ContactDirection } from "../DeviceComponents/Contact";
import { Motion } from "../DeviceComponents/Motion";
import { TvDirection, Tv } from "../DeviceComponents/Tv";
import { WashingMachine } from "../DeviceComponents/WashingMachine";

export const allDevices: { [deviceId: string]: DeviceDataKind } = {
    "1": {
        id: "1",
        kind: "DIMMER",
        component: Dimmer,
        note: "Dinning Room Light",
        position: [457, 367],
        attributes: {},
        label: "",
        name: "",
    },
    "2": {
        id: "2",
        kind: "DIMMER",
        component: Dimmer,
        note: "Living Room Light",
        position: [502, 487],
        attributes: {},
        label: "",
        name: "",
    },
    "4": {
        id: "4",
        kind: "DIMMER",
        component: Dimmer,
        note: "Kitchen Room Light",
        position: [522, 222],
        attributes: {},
        label: "",
        name: "",
    },
    "73": {
        id: "73",
        kind: "DIMMER",
        component: Dimmer,
        note: "Corridor",
        position: [157, 257],
        attributes: {},
        label: "",
        name: "",
    },
    "11": {
        id: "11",
        kind: "SWITCH",
        component: LightSwitch,
        note: "Alicia",
        position: [67, 184],
        attributes: {},
        label: "",
        name: "",
    },
    "129": {
        id: "129",
        kind: "DIMMER",
        component: Dimmer,
        note: "Bathroom",
        position: [247, 347],
        attributes: {},
        label: "",
        name: "",
    },
    "7": {
        id: "7",
        kind: "SWITCH",
        component: LightSwitch,
        note: "Garage",
        position: [157, 647],
        attributes: {},
        label: "",
        name: "",
    },
    "3": {
        id: "3",
        kind: "SWITCH",
        component: LightSwitch,
        note: "Entry",
        position: [327, 496],
        attributes: {},
        label: "",
        name: "",
    },
    "9": {
        id: "9",
        kind: "SWITCH",
        component: LightSwitch,
        note: "Jacob",
        position: [232, 182],
        attributes: {},
        label: "",
        name: "",
    },
    "8": {
        id: "8",
        kind: "SWITCH",
        component: LightSwitch,
        note: "Playroom",
        position: [387, 182],
        attributes: {},
        label: "",
        name: "",
    },
    "290": {
        id: "290",
        kind: "DIMMER",
        component: Dimmer,
        note: "Master Bathroom",
        position: [37, 327],
        attributes: {},
        label: "",
        name: "",
    },
    "131": {
        id: "131",
        kind: "DIMMER",
        component: Dimmer,
        note: "Master Bedroom",
        position: [97, 422],
        attributes: {},
        label: "",
        name: "",
    },
    "13": {
        id: "13",
        kind: "DIMMER",
        component: Dimmer,
        note: "Master Walkin Closet",
        position: [247, 422],
        attributes: {},
        label: "",
        name: "",
    },
    "67": {
        id: "67",
        kind: "CONTACT",
        component: Contact,
        note: "Outside Garage Door",
        position: [2, 554],
        direction: ContactDirection.East,
        attributes: {},
        label: "",
        name: "",
    },
    "32": {
        id: "32",
        kind: "CONTACT",
        component: Contact,
        note: "Indoor Garage Door",
        position: [302, 530],
        direction: ContactDirection.East,
        attributes: {},
        label: "",
        name: "",
    },
    "31": {
        id: "31",
        kind: "CONTACT",
        component: Contact,
        note: "Front Door",
        position: [310, 576],
        direction: ContactDirection.South,
        attributes: {},
        label: "",
        name: "",
    },
    "27": {
        id: "27",
        kind: "CONTACT",
        component: Contact,
        note: "Master Closet Door",
        position: [199, 440],
        direction: ContactDirection.East,
        attributes: {},
        label: "",
        name: "",
    },
    "38": {
        id: "38",
        kind: "CONTACT",
        component: Contact,
        note: "Alicia Bedroom Window",
        position: [52, 122],
        direction: ContactDirection.SlideRight,
        attributes: {},
        label: "",
        name: "",
    },
    "227": {
        id: "227",
        kind: "CONTACT",
        component: Contact,
        note: "Living Room Left Window",
        position: [402, 616],
        direction: ContactDirection.SlideRight,
        attributes: {},
        label: "",
        name: "",
    },
    "226": {
        id: "226",
        kind: "CONTACT",
        component: Contact,
        note: "Living Room Right Window",
        position: [507, 616],
        direction: ContactDirection.SlideLeft,
        attributes: {},
        label: "",
        name: "",
    },
    "18": {
        id: "18",
        kind: "CONTACT",
        component: Contact,
        note: "Kitchen Door",
        position: [596, 150],
        direction: ContactDirection.SlideDown,
        attributes: {},
        label: "",
        name: "",
    },
    "68": {
        id: "68",
        kind: "CONTACT",
        component: Contact,
        note: "Master Bedroom Left Window",
        position: [2, 453],
        direction: ContactDirection.SlideUp,
        attributes: {},
        label: "",
        name: "",
    },
    "28": {
        id: "28",
        kind: "MOTION",
        component: Motion,
        note: "Master Bathroom",
        position: [62, 335],
        path: [
            [13, 342],
            [100, 342],
        ],
        attributes: {},
        label: "",
        name: "",
    },
    "16": {
        id: "16",
        kind: "MOTION",
        component: Motion,
        note: "Garage Motion",
        position: [240, 685],
        path: [
            [240, 685],
            [285, 565],
            [95, 565],
            [220, 640],
            [212, 720],
            [70, 725],
            [60, 790],
        ],
        attributes: {},
        label: "",
        name: "",
    },
    "29": {
        id: "29",
        kind: "MOTION",
        component: Motion,
        note: "Corridor Motion",
        position: [220, 275],
        path: [
            [330, 280],
            [255, 280],
            [115, 280],
            [255, 280],
            [330, 280],
        ],
        attributes: {},
        label: "",
        name: "",
    },
    "30": {
        id: "30",
        kind: "MOTION",
        component: Motion,
        note: "Bathroom Motion",
        position: [270, 325],
        path: [
            [270, 325],
            [230, 345],
            [290, 405],
        ],
        attributes: {},
        label: "",
        name: "",
    },
    "24": {
        id: "24",
        kind: "MOTION",
        component: Motion,
        note: "Dinner Motion",
        position: [412, 282],
        path: [
            [500, 320],
            [545, 365],
            [510, 440],
            [370, 405],
        ],
        attributes: {},
        label: "",
        name: "",
    },
    "46": {
        id: "46",
        kind: "TV",
        component: Tv,
        note: "Living Room TV",
        position: [597, 510],
        direction: TvDirection.West,
        radius: [25, 40],
        attributes: {},
        label: "",
        name: "",
        wattThreashold: 10,
    },
    "44": {
        id: "44",
        kind: "TV",
        component: Tv,
        note: "Computer Monitor",
        position: [402, 572],
        direction: TvDirection.West,
        radius: [15, 20],
        attributes: {},
        label: "",
        name: "",
        wattThreashold: 50,
    },
    "25": {
        id: "25",
        kind: "WASHINGMACHINE",
        component: WashingMachine,
        note: "WashingMachine",
        position: [112, 537],
        width: 30,
        attributes: {},
        label: "",
        name: "",
    },
};
